name: FormatterAuto
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - 'release/**'
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: npm ci
        run: npm ci
      - name: Run Prettier
        run: npm run prettier
      - name: Run Eslint
        run: npm run eslint:fix
      - name: Check diff exists
        run: |
          git add -N .
          git diff
          line=`git diff | wc -l`
          if [ $line -gt 0 ]; then
            echo "You need to format before commit"
            git diff
            exit -1
          fi
